### ISSUE TITLE
[Bug][macOS] Playback timer resets

### ISSUE THREAD

**Issue by SurlySteve** [gdavis/Mimir-Feedback#117]
When I pause playback of an episode Occasionally when I resume playback the timer has moved back to the beginning of the episode.

![Screen Shot 2022-05-25 at 6 50 03 AM](https://user-images.githubusercontent.com/102470092/170249460-c191f2a6-1774-40eb-94be-3b781fc0abb8.png)

**Comment by gdavis** [comment]
Thanks @SurlySteve. I'll get this in the queue to get looked at

**Comment by gdavis** [comment]
Hey @SurlySteve – this issue was happening while the app was running right? Not after restarting the app? 

I've found an issue seeking to the episode's last position when restarting the app, but this sounds like it was happening while everything is running. Can you confirm that for me? Thanks!

**Comment by SurlySteve** [comment]
Good morning Grant,

Thank you for the apps and all your work to ensure they are quality products.  Yes, these issues occur while everything is running, I rarely close Mimir unless TestFlight tells me to do so.

Cheers!

Steve

**Comment by gdavis** [comment]
Okay, great! Thank you for the quick response @SurlySteve . I'm working hard on a fix today!

**Comment by gdavis** [comment]
@SurlySteve I just released new versions for both iOS and macOS that has a fix for this issue. Give it a shot and let me know how it goes!

**Comment by SurlySteve** [comment]
Grant

My iPad and iPhone both had the option in TestFlight to install Mimir 1.0.0 (90) but TestFlight on my iMac has Mimir for macOS 1.5.0 (116) and did not offer an option to update.  Mimir on the iPad shows an unplayed episode count of over 11,000 where the iMac (399) and iPhone (403) are much closer.

Steve

**Comment by gdavis** [comment]
@SurlySteve it looks like Apple had a hiccup releasing the macOS update to all testers. I got an email a couple of hours ago saying it should now be available though, so see if you can update now.

I think you're seeing big mismatches in the unplayed counts on your mac because you've had that version for a while now, and I've changed how unplayed episodes are tracked and the database has not been updated. I'll make a new ticket and see if I can do a better job of getting users with the older database configuration up to date. The counts *should* eventually get back in sync when the podcast feed is updated with new episodes, but I'll work on doing a better job at handling that.

**Comment by SurlySteve** [comment]
Good morning Grant,

Yes, I saw the update come through a bit ago, my iMac is now up and running Mimir for macOS 1.5.0 (117).

I believe I have iCloud sync set up on all device so I had assumed my settings would match on the iMac, iPad, and iPhone.

Cheers!

Steve
