### ISSUE TITLE
[BUG][iOS] several buttons seem to lack implementation

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#26]
These buttons seem to be not working

![image](https://user-images.githubusercontent.com/705971/159809350-10f94458-f6d4-40d6-800a-212031e46738.jpeg)

**Comment by gdavis** [comment]
The button in the top right is a quick "collapse-all groups" button. Since you don't have any groups, it appears to do nothing. I've been wrestling with how to better improve this functionality, but for starters I'll hide that button if there are no groups in the library.

- [ ] Hide collapse all groups button when there are no groups in the library

As for the top left plus button, choosing "Add Group" should present you with an alert to name the new group you want to add. Are you not seeing this alert pop up?
<img width="262" alt="image" src="https://user-images.githubusercontent.com/110691/159836115-44c9c50d-9ca6-4b78-aa6c-5a27594ac0bc.png">

The "Add RSS Feed" button should also present you an alert to paste in a URL for the RSS feed you want to add. Is this not appearing for you either? If not, can you recall what the last alert to display like this might have been? It could be the that the app has an unfinished alert operation hung up that is preventing new ones from appearing.

**Comment by ileacristian** [comment]
Interesting... now those alerts work but i'm not sure how I got it in this state where they don't work.
I still have a personal list of bugs that happened but i'm not 100% sure how to reproduce.

I had a similar issue with the alert not showing up when trying to "restore to default settings" in the settings screen.
After a restart it would seem to work again.

**Comment by gdavis** [comment]
This has been fixed and is being released in iOS app version 80
