### ISSUE TITLE
[iOS][Bug] Library temporarily disappeared

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#54]
1. Library disappeared on the iOS app
2. While this was happening the Mac app opened normally and the library showed (on mac).
3. Only after i added a new podcast from discover (on iOS) the library reappeared

https://user-images.githubusercontent.com/705971/160217153-9fea9dc3-c7cc-47fb-9f9a-c2dcdb031ad3.MOV

**Comment by gdavis** [comment]
1ileaCristian: it recovered after i added something
1ileaCristian: on mac they appeared
1ileaCristian: so it didn't actually "dissapear" from the cloud since the mac app started OK while the iOS app was not showing the library...
1ileaCristian: no, wait
1ileaCristian: 1. library dissapeared on iphone 2. i opened the mac app - they showed 3. i added something from discover on iOS and then they showed back on the iOS app
1ileaCristian: but if i wouldn't have added new item, even after multiple restart, the library was showing empty

**Comment by gdavis** [comment]
This should be fixed with the latest release that reworks how iCloud sync works. Please let me know if you have any more library issues like this @ileacristian
