### ISSUE TITLE
[iOS] Tell the User That the Mimir AudioEngine is not being used

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#65]
**Is your feature request related to a problem? Please describe.**
I accidentally added a video podcast and when I tried to change the Playback speed, I heard the Chipmunks right away.

**Describe the solution you'd like**
Might be interesting for the user to know that the AudioEngine can't handle Video feeds and the quality should be a lot better in faster playback speeds. I popup would do, to tell the User that it is out of your hands😇

**Describe alternatives you've considered**

**Additional context**
https://podcasts.apple.com/de/podcast/this-week-in-google-video/id593120919?l=en

**Comment by gdavis** [comment]
I agree. Will look into adding some kind of callout when playing video episodes that lets the users know that the audio effects and better audio quality is not enabled for video.

**Comment by gdavis** [comment]
With the updated layout added today for some extra image space, I think the best solution is to add button that says "Effects Disabled" that is overlaid on the podcast image in Now Playing. When tapped, it will display an alert that tells the user that the custom audio effects are disabled because of an unsupported audio (or video) file type.

Will be adding this in the next couple days.

**Comment by gdavis** [comment]
Okay this took me more than a couple of days to get to, but this has now been added! A new warning icon will now display in the lower player button bar when playing a video episode. Tapping the button will present an alert explaining that audio effects are disabled for video/unsupported file types. This UI setup is used for both macOS and iOS

This will be part of the next release!
