### ISSUE TITLE
[iOS][macOS] adding sharing

### ISSUE THREAD

**Issue by svranyes** [gdavis/Mimir-Feedback#86]
Integrating podcasts into the rest of what you are doing would be super helpful. Being able to share to other apps via the sharing capability of macOS and iOS would be ideal.  A user story here would be... 

* while listening to a podcast allow the user to share either the podcast episode, the specific point in time of the podcast episode, or the podcast itself. The sharing could be to an app like Pocket, Apple Notes, Reminders, etc... . The link (if following what other apps are doing) might be "mimir://...."
* what gets shared out by Mimir to these apps is a link that the user can then click on and be brought back into Mimir in the proper context - the podcast episode, the point in time in the episode, or the podcast subscription itself. 

This kind of capability would go a long way in making podcasts an even more first class resource in the environment. 

thanks for considering!

**Comment by gdavis** [comment]
Hey @svranyes 
I definitely agree sharing should be added to both mac and iOS platforms. I have some hurdles to get over to technically achieve this, but do know its on my list of hot topics to take care of. I'd like to get this in before launching the iOS 1.0 app, but it might end up coming in a later update since the 1.0 version and 1.5 for mac have so many new features already. I imagine this would be a big enough addition with enough stuff to test it could be part of its own minor version release. 

Adding to the list to keep track of its progress!

**Comment by gdavis** [comment]
Bumping up to high priority for next release. Also need to include the ability to share the downloaded MP3 file for episodes so they can be transferred to other apps/devices.

**Comment by gdavis** [comment]
Just an update on this: other features took priority over the last few months to get the player and playlist features in a solid state. I'm currently planning on addressing this after the next feature update that will include CarPlay.

**Comment by gdavis** [comment]
This feature is now in active development.
